/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

declare const self: ServiceWorkerGlobalScope;

const CACHE = `am5-mobo-cache-${version}`;

// Assets to precache: build files (immutable JS/CSS generated by Vite) + static files (manifest, icons)
const ASSETS = [...build, ...files];

self.addEventListener('install', (event: ExtendableEvent) => {
  async function precacheAssets() {
    const cache = await caches.open(CACHE);
    try {
      await cache.addAll(ASSETS);
    } catch {
      // Graceful fallback if any asset fails to fetch individually
      for (const asset of ASSETS) {
        try {
          await cache.add(asset);
        } catch {
          // ignore failed individual asset
        }
      }
    }
  }

  event.waitUntil(precacheAssets().then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event: ExtendableEvent) => {
  async function cleanupCaches() {
    const keys = await caches.keys();
    for (const key of keys) {
      if (key !== CACHE) {
        await caches.delete(key);
      }
    }
  }

  event.waitUntil(cleanupCaches().then(() => self.clients.claim()));
});

self.addEventListener('fetch', (event: FetchEvent) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);

  // Ignore non-http/https schemes
  if (!url.protocol.startsWith('http')) return;

  // 1. Static assets & immutable build files: Cache-First strategy
  const isStaticAsset =
    ASSETS.includes(url.pathname) ||
    url.pathname.startsWith('/_app/immutable/') ||
    url.pathname.startsWith('/icons/') ||
    url.pathname === '/favicon.png' ||
    url.pathname === '/manifest.webmanifest';

  if (isStaticAsset) {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        const cached = await cache.match(event.request);
        if (cached) return cached;

        try {
          const response = await fetch(event.request);
          if (response.ok) {
            cache.put(event.request, response.clone());
          }
          return response;
        } catch {
          return new Response('Asset not found offline', {
            status: 404,
            statusText: 'Not Found'
          });
        }
      })()
    );
    return;
  }

  // 2. Data files (e.g. /data/boards.json, /data/build-meta.json): Network-First strategy
  const isDataFile = url.pathname.startsWith('/data/') || url.pathname.endsWith('.json');

  if (isDataFile) {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        try {
          const response = await fetch(event.request);
          if (response.ok) {
            cache.put(event.request, response.clone());
          }
          return response;
        } catch {
          const cached = await cache.match(event.request);
          if (cached) return cached;

          return new Response(
            JSON.stringify({
              error: 'offline',
              message: 'Data unavailable offline'
            }),
            {
              status: 503,
              headers: { 'Content-Type': 'application/json' }
            }
          );
        }
      })()
    );
    return;
  }

  // 3. Navigation requests (HTML pages): Network-First with offline SPA fallback
  if (event.request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const cache = await caches.open(CACHE);
        try {
          const response = await fetch(event.request);
          if (response.ok) {
            cache.put(event.request, response.clone());
          }
          return response;
        } catch {
          const cached = await cache.match(event.request);
          if (cached) return cached;

          // Fallback to cached root or index.html for SPA routing
          const rootFallback = (await cache.match('/')) || (await cache.match('/index.html'));
          if (rootFallback) return rootFallback;

          return new Response(
            '<!doctype html><html><body style="background:#0d1117;color:#fff;font-family:sans-serif;text-align:center;padding:50px;"><h2>AM5 Mobo Compare</h2><p>You are offline and this page has not been cached yet.</p></body></html>',
            {
              status: 503,
              headers: { 'Content-Type': 'text/html; charset=utf-8' }
            }
          );
        }
      })()
    );
    return;
  }

  // 4. Default handler for third-party assets (CDNs, icons, etc.): Stale-while-revalidate / cache-first
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const cached = await cache.match(event.request);

      const networkFetch = fetch(event.request)
        .then((response) => {
          if (response.ok) {
            cache.put(event.request, response.clone());
          }
          return response;
        })
        .catch(() => null);

      if (cached) {
        // Return cached immediately; update cache in background
        networkFetch.catch(() => {});
        return cached;
      }

      const freshResponse = await networkFetch;
      if (freshResponse) return freshResponse;

      return new Response('Network error and no offline cache available', {
        status: 503,
        statusText: 'Service Unavailable'
      });
    })()
  );
});
